### ISSUE TITLE
Linter question ruff vs black

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/data-management#10]
@andersy005 @katamartin thanks for working on improving the CI here. I was just curious about the [code linter setup with pre-commit](https://github.com/leap-stc/data-management/blob/main/.pre-commit-config.yaml): Why are we using both ruff and black? 
Am I wrong in thinking that ruff replaces black for most parts? Maybe this is just for linting notebooks with black-jupyter?

**Comment by andersy005** [comment]
My understanding is that `ruff` is not necessary a replacement for black

Per the docs: https://beta.ruff.rs/docs/faq/#is-ruff-compatible-with-black

> As a project, Ruff is designed to be used alongside Black and, as such, will defer implementing stylistic lint rules that are obviated by autoformatting.

**Comment by jbusecke** [comment]
Oh interesting! Thanks for the link and correction!
