### ISSUE TITLE
Catalog Feature: Link to cards for easier sharing

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/data-management#129]
As the catalog gets populated with more datasets, I think we need a way to link to a specific dataset. 

For example: If I want to load the `AWS NOAA Optimum Interpolated SST` right now, I have to navigate to the url, and either scroll or filter for the dataset. This is either slow, or might get error prone (when more datasets with similar names are added for instance).

I would like to be able to link to a specific dataset, so that I can use that link in docs, share with people on github etc. 

cc @katamartin @andersy005

**Comment by andersy005** [comment]
👋🏽 @jbusecke, 

kata and i have discussed this issue and identified two potential solutions, each with varying levels of effort required:

option 1: update the URL state based on user searches. currently, when you visit `catalog.leap.columbia.edu` and search for "AWS NOAA Optimum Interpolated SST," the feedstocks are filtered, but the search state is not encoded in the URL. It would be great to update the URL to something like `https://catalog.leap.columbia.edu/?search=AWS%20NOAA%20Optimum%20Interpolated%20SST`. this way, when someone shares the URL with others, they will see the same search results.

option 2: create dedicated pages for each feedstock. with this approach, if someone wanted to share or navigate to "AWS NOAA Optimum Interpolated SST," the link would be something like `https://catalog.leap.columbia.edu/AWS%20NOAA%20Optimum%20Interpolated%20SST`. however, this option requires some design work before implementation.

option 1 is a low-hanging fruit that we can implement in the near future, while option 2 is a more comprehensive solution that we can work on when we have more time and resources.

What do you think about these options?

**Comment by jbusecke** [comment]
I think that option 2 is ultimately the best solution, but 1 seems like a good intermediate solution. 
would it be possible to have a "share" button that copies the url+search to the clipboard?

**Comment by andersy005** [comment]
Closing this as it has been implemented in 

- https://github.com/carbonplan/leap-data-catalog/pull/82
