### ISSUE TITLE
New Dataset [Subseasonal Rodeo Dataset]

### ISSUE THREAD

**Issue by AlexandreRebiere** [leap-stc/data-management#14]
### Dataset Name

The SubseasonalRodeo Dataset

### Dataset URL

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IHBANG

### Description

A benchmark dataset for training and evaluating subseasonal forecasting systems—systems predicting temperature or precipitation 2-6 weeks in advance—in the western contiguous United States. This dataset gathers various datas concerning precipitation and temperature, used in the Rodeo forecasting model.

### Size

The datasets consists of 160 Mb files in a total of 10 GB.

### License

Unknown

### Data Format

HDF

### Data Format (other)

.h5

### Access protocol

HTTP(S)

### Source File Organization

The source files aren't quite organized in this dataset. It gathers datas of different parameters (precipitation, wind, temperature...) from different eras.

### Example URLs

```shell
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IHBANG
```

### Authorization

No; data are fully public

### Transformation / Processing

There's nothing to modify in this dataset. The forecasting model is able to work with this dataset. No more analysis is needed.

### Target Format

Other

### Comments

they have to keep the same name and the same format (.h5)

**Comment by jbusecke** [comment]
Is there any ability to combine some of these datasets? Or should each file be mapped to a single zarr store?

**Comment by AlexandreRebiere** [comment]
Actually no... each file is named for a certain reason and used at different moments in the algorithm. Each file may have to exist in its own zarr...

**Comment by jbusecke** [comment]
Closing this as wontfix due to inactivity.
