### ISSUE TITLE
Add 60M to eNATL dataset name

### ISSUE THREAD

**Issue by norlandrhagen** [leap-stc/data-management#148]
Now that a [600m eNATL dataset has been proposed](https://github.com/leap-stc/data-management/issues/147), we should modify the catalog entry for the eNATL dataset so that 60m is part of the name.

**Comment by jbusecke** [comment]
Can we try to keep both receipes in the same feedstock?

**Comment by norlandrhagen** [comment]
https://github.com/leap-stc/eNATL_feedstock/commit/d9e20df9a7abdca16ed20414a3825fc184c4127a
