### ISSUE TITLE
Can we configure the 'engine' argument in the displayed xarray/python repr?

### ISSUE THREAD

**Issue by norlandrhagen** [leap-stc/data-management#150]
Thinking about if we add any virtualzarr reference datasets to the catalog. It would be nice if we could update the default 'engine="zarr"` with a value from either the meta.yaml or the catalog.yaml.

<img width="424" alt="image" src="https://github.com/user-attachments/assets/9a434b0b-38ed-4e00-8b65-0f62aae6e3fc">

`ds = xr.open_dataset(<reference_file_url>, engine="kerchunk", chunks={})`

**Comment by norlandrhagen** [comment]
Yup! I think if Kerchunk is installed in the env, it should work. 

Maybe we can default to engine='zarr' and then if engine_type exists as a field `catalog.yaml`, we supply it there?

Or we could backfill all the catalog.yaml's. 

Thanks @andersy005!

**Comment by andersy005** [comment]
perfect! can you point me to existing stores i can use for testing purposes?

**Comment by norlandrhagen** [comment]
Totally!

```python

import xarray as xr 

store = 'https://rice1.osn.mghpcc.org/carbonplan/virtual_datasets/gridmet/gridmet_1979_2020.parquet'

ds = xr.open_dataset(store, engine="kerchunk", chunks={})
combined_ds
```

**Comment by norlandrhagen** [comment]
I can also put a reference on the leap osn bucket or the LEAP google storage if that helps.

**Comment by andersy005** [comment]
> Totally!
> 
> ```python
> import xarray as xr 
> 
> store = 'https://rice1.osn.mghpcc.org/carbonplan/virtual_datasets/gridmet/gridmet_1979_2020.parquet'
> 
> ds = xr.open_dataset(store, engine="kerchunk", chunks={})
> combined_ds
> ```


thank you, @norlandrhagen! i was able to use this for testing purposes

**Comment by jbusecke** [comment]
Thanks folks. Great to see all of these improvements moving quickly!
