### ISSUE TITLE
New Dataset [MetaFlux]

### ISSUE THREAD

**Issue by AlexandreRebiere** [leap-stc/data-management#16]
### Dataset Name

MetaFlux: Meta-learning global carbon fluxes from sparse spatiotemporal observations

### Dataset URL

https://zenodo.org/record/7761881#.ZFj3LC3pNQI

### Description

MetaFlux is a global, long-term carbon flux dataset of gross primary production and ecosystem respiration that is generated using meta-learning. This dataset will be added to the existing rodeo forecast model in order to improve its performances. 

### Size

The datasets consists of 200MB files with a total of 53.3GB

### License

Unknown

### Data Format

NetCDF

### Data Format (other)

.nc

### Access protocol

HTTP(S)

### Source File Organization

data is organised with a daily resolution (One file per month from 2001 to 2021) and a monthly resolution (One file per year from 2001 to 2021.).  

### Example URLs

```shell
https://zenodo.org/record/7761881#.ZFj3LC3pNQI
```

### Authorization

No; data are fully public

### Transformation / Processing

Data seems to be already well organized. We will work on those datas without any modifications.

### Target Format

Zarr

**Comment by jbusecke** [comment]
Finalized monthly dataset can be found here:
```python
ds = xr.open_dataset('gs://leap-persistent/data-library/metaflux-gpp-reco-monthly-595733423-4998601040-1/METAFLUX_GPP_RECO_monthly.zarr', engine='zarr')
```

**Comment by jbusecke** [comment]
The daily dataset is still not run reliably. Will investigate tomorrow.

**Comment by jbusecke** [comment]
Got the daily dataset to run:
```python
import xarray as xr
url = 'gs://leap-persistent/data-library/metaflux-gpp-reco-monthly-595733423-4998601040-1/METAFLUX_GPP_RECO_monthly.zarr'
ds = xr.open_dataset(url, engine='zarr', chunks={})
```

**Comment by jbusecke** [comment]
@AlexandreRebiere @alexx-frcs please comment here and on #17 if there are any issues with the data! 

FYI: I will be on vacation starting tomorrow until June 6. Might very infrequently look at git

**Comment by jbusecke** [comment]
I have moved everything relevant to this issue into https://github.com/leap-stc/metaflux_feedstock and this will be part of the new LEAP catalog.
