### ISSUE TITLE
Add published ClimSim Dataset via pangeo forge

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/data-management#28]
Thanks to a lot of work by @sungdukyu @jerrylin96 and many others, the E3SM-MMF(ne4) aka [ClimSim](https://github.com/leap-stc/ClimSim) dataset is now available on huggingface. 

I would like to reingest it via pangeo-forge to make this workflow entirely reproducible!

- [ ] Wait for final naming/publication

**Comment by shoyer** [comment]
We (at Google) would be excited to be able to play around with the ARCO version of ClimSim. I think this could make for an interesting training dataset for some of our ML weather models :)

**Comment by sungdukyu** [comment]
@shoyer  (Sorry for the dumb question.) What is "ARCO"?

**Comment by rabernat** [comment]
"Analysis-Ready, Cloud Optimized". See [this paper](https://ieeexplore.ieee.org/document/9354557) for a longer definition.

So basically:
- Converting the data to a single Zarr dataset
- Augmenting some of the missing / nonexistent metadata
- Placing in cloud object storage

That's the goal here.

**Comment by sungdukyu** [comment]
@rabernat Thanks for the clarification. One challenge would be the gigantic size of the high-res dataset, ~41TB. (BTW, we already have the _'Zarr'-ed_ real-go low-res dataset in LEAP cloud storage.)

**Comment by sungdukyu** [comment]
Yes, absolutely, Zarr's the way to go for these huge datasets. However, what I meant was processing netcdf files (>400k files totaling 41TB) to a single Zarr file. It took quite a long time just for a low res dataset (same file number but much smaller size at several 100s GB). Maybe there's a more efficient way of doing this, I guess.

**Comment by rabernat** [comment]
> Maybe there's a more efficient way of doing this, I guess.

@sungdukyu  🤝 Meet [Pangeo Forge](https://pangeo-forge.org/)!

**Comment by sungdukyu** [comment]
@rabernat Thanks! Seems like my bakery was suboptimal. (https://pangeo-forge.org/pangeo-forge-diagram.png)

**Comment by jbusecke** [comment]
Since we have the right audience here, would it make sense to explore uploading a [zarr store directly to huggingface](https://github.com/huggingface/datasets/issues/4096)?

**Comment by rabernat** [comment]
Let's not try to mix in huggingface-related development work. Let's just try to ship the ClimSim dataset as fast as possible by whatever means necessary.

**Comment by jbusecke** [comment]
I can try to spend some time on this next week! In case somebody wants to start before that, starting a recipe PR in our [LEAP feedstock](https://github.com/leap-stc/data-management/tree/main/feedstock) would be the way to go.

**Comment by cisaacstern** [comment]
@jbusecke could you push the work we began together on this as a PR? I have some time I can devote to this and would love to pick up where we left off.

**Comment by jbusecke** [comment]
See #33, sorry for the delay.
