### ISSUE TITLE
New Dataset [TWSA model input data]

### ISSUE THREAD

**Issue by PalIre** [leap-stc/data-management#29]
### Dataset Name

TWSA model input data

### Size

The dataset consists of 60 files: 30 files contain input data including LCSIF (716 MB), 30 do not include LCSIF (949 MB)

### License

Unknown

### Data Format

Other (describe below)

### Data Format (other)

npy

### Access protocol

HTTP(S)

### Source File Organization

There is one file per each climatic region. Each file contains monthly data of TWSA, precipitation, air temperature, relative humidity, solar radiation, LCSIF (or not) from 2000 to 2017 for each pixel of the climatic region.

### Authorization

None

### Target Format

Zarr

**Comment by jbusecke** [comment]
Dear @PalIre, 

thanks for raising this issue. There is however some crucial information missing here. Could you edit your post and at the minimum tell us where the data resides at the moment (e.g. provide an example link where one can publicly download a sample file). 

Ultimately we also need a license for the file, but we can figure this out along the way.

Thank you

**Comment by PalIre** [comment]
Dear @jbusecke,

thanks for your message. I was able to figure out a temporary solution for my data storage. So at the moment I do not need to move forward with this request. 

Thank you

**Comment by jbusecke** [comment]
Ok thanks @PalIre. Closing this now, feel free to reopen if you want to make this dataset more broadly accessible!
Would also be curious where you ended up storing your data?
