### ISSUE TITLE
Add AVISO SSH (on OSN) to LEAP catalog

### ISSUE THREAD

**Issue by cisaacstern** [leap-stc/data-management#34]
Per @dcherian's request, I copied https://catalog.pangeo.io/browse/master/ocean/sea_surface_height/ to Pangeo Forge's Open Storage Network (OSN) allocation. It is accessible as follows:

```python
import xarray as xr
ds = xr.open_dataset("https://ncsa.osn.xsede.org/Pangeo/pangeo-cmems-duacs", consolidated=True, engine="zarr")
```

This can be considered a temporary fix to make this dataset available ASAP. We should write and run a Pangeo Forge recipe pointing at the original source data for this eventually, for improved data provenance.

@jbusecke suggested we add this dataset to the LEAP catalog here. Julius, is there a standard procedure for doing this?

**Comment by jbusecke** [comment]
The instructions worked super well. Thanks @andersy005! 
Fixed a small typo in #59 and submitted #60 to add the aviso data.
