### ISSUE TITLE
Build catalog website preview for PRs?

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/data-management#61]
It would be really neat if there would be a preview of the catalog from a PR, so that users do not have to wait for a merge and open another PR to fix things. 

@andersy005 this is not a high priority, but just wondering what you think about this?

**Comment by cisaacstern** [comment]
I think this would need to happen on whichever repo is building the vercel site? If there is a way to do it from here, that'd be awesome tho!

**Comment by andersy005** [comment]
With the addition of previews in [PR #89](https://github.com/leap-stc/data-management/pull/89), we should now be able to load the catalog page and point to different catalogs for previewing. Whenever a user opens a PR, we create a ["deployment"](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) that points to the catalog version in the pull request branch. To access this deployment, click on the View deployment button. Below is a screenshot of the button:

![Screenshot 2024-03-09 at 08 02 21](https://github.com/leap-stc/data-management/assets/13301940/c9e0f861-4d1b-4aa9-b75b-40d0e3512978)

Cc @jbusecke / @katamartin  for visibility
