### ISSUE TITLE
 CESM2.2 CAM6 Perturbed Parameter Ensemble (PPE) PD Time Series Monthly Averages

### ISSUE THREAD

**Issue by yiqioyang** [leap-stc/data-management#95]
### Dataset Name

 CESM2.2 CAM6 Perturbed Parameter Ensemble (PPE) PD Time Series Monthly Averages

### Dataset URL

https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2.cam6.ppe.pd_timeseries.atm.hist.monthly_ave.html

### Description

This dataset will be used as the dataset for us to test newly developed emulators. The PPE will be also used for parameter estimation using the emulator and inversion method that we come up with. 

Note that this is only a subset of the complete CESM2.2 CAM6 Perturbed Parameter Ensemble (PPE) (see: https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2.cam6.ppe.html). We focus on CESM2.2-CAM6 PPE PD Time Series Monthly Averages for now as a testbed that might be used for the LEAP Summer REU and Momentum Programs. 

 

### Size

Unknown 

### License

Unknown (see 

### Data Format

NetCDF

### Access protocol

HTTP(S)

### Source File Organization

Within the link given above, there are many links under the "Child Datasets". 
Each link within the "Child Datasets" corresponds to a variable that is generated from the climate model simulation. 
Within each link, there is a "Download Options" button. 

Clicking on the "Download Options", there are 262 nc files. 
The 262 nc files are different  in the parameter values that are used during the running of the climate model. 

All nc files share the same coordinates in time and space. Their difference is the variable that they store and the parameters adopted to generate the simulation.  This can be seen in the file names, for example: 
File name "cc_PPE_250_ensemble_PD.000.h0.ACTNI.nc" suggests that the variable it stores is ACTNI, and it is from the 000th simulation, namely from the first set of parameters. 

### Example URLs

```shell
https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/projects/ppe/cam_ppe/rerun_PPE_250/PD/PD_timeseries/PPE_250_ensemble_PD.000/atm/hist/cc_PPE_250_ensemble_PD.000.h0.ACTNI.nc?api-token=TGLy7EMWBpimnosAbrfUyvvlyAHRvHUjzrna0Mqz
```

### Authorization

No; data are fully public

### Transformation / Processing

No need for right now. 

### Target Format

Zarr

### Comments

The data needs to be accessed with a OrcID/google account.

**Comment by jbusecke** [comment]
Thanks for submitting the request @yiqioyang. 

I just tried to follow the links and got as far as this:
<img width="778" alt="image" src="https://github.com/leap-stc/data-management/assets/14314623/c129de15-5bbc-44bc-b48b-f2710e2a6c22">

So I think getting the authentication right will be the biggest issue here. Could you find out if they provide HTTP username/password-based authentication for these datasets at all?

**Comment by yiqioyang** [comment]
Hi @jbusecke , it is strange that I didn't get to see the screenshot that you attached here. 
Can you try this link (second one in my post): https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2.cam6.ppe.html ?
After this link, you will see:

![Screenshot 2024-04-11 at 9 51 10 AM](https://github.com/leap-stc/data-management/assets/36542868/53e86207-2ce3-403c-87f6-558306966aa1)

Click on the "CESM2.2-CAM6 PPE PD Time Series", and then select "CESM2.2-CAM6 PPE PD Time Series Monthly Averages", which will show the data we want for now. In this way to access the data, I could either simply get the download link or need to sign-in with an orcid or google account (not sure if this would cause the similar issue with authentication). Can you give it a try and see if that works?

Or let me know if I made myself clear. Thanks!

**Comment by jbusecke** [comment]
I did click that, signed in, and then got an authorization denied?

**Comment by jbusecke** [comment]
I saw [here](https://www.earthsystemgrid.org/help/download-help.html) that they give you an option to get a wget script? Can you generate that and post it here (or send it via slack). I hope we can reverse engineer this to get a simple http link .

**Comment by jbusecke** [comment]
Or even simpler maybe, can you click through there and copy the link under the download button? 

Happy to iterate on this some time next week, its just hard to progress here without access.

**Comment by yiqioyang** [comment]
Hi Julius, thanks for the patience, and yes, will get those to you once

**Comment by yiqioyang** [comment]
Hi Julius, yes, will get back to you when I hear some updates (what variables we want and etc) from others. 
Thanks for the patience!
